### ISSUE TITLE
Cannot unlist

### ISSUE THREAD

**Issue by symmetrium** [Nikschavan/unlist-posts#17]
Hi! This could be a problem with my specific setup, but just a heads up in case someone else experiences the same problem: for some reason I was not able to re-list a specific custom post - it seems that the unchecked checkbox is not being saved, and the check comes back when changes to post are saved. 

I had to change the value of unlist_posts in the mySQL options table. (wordpress 4.8 / plugin version: 1.0.2) to get the option unchecked.

(Note: I noticed that the value contains the post's id (62343) multiple times - does that mean that each time I tried to save a new value was added to the array? )

the value for unlist_posts: before I edited it was: 

a:76:{i:1;i:62579;i:3;i:62580;i:5;i:62581;i:8;i:62582;i:11;i:62343;i:12;i:62583;i:13;i:62343;i:14;i:62586;i:15;i:62343;i:16;i:62587;i:17;i:62343;i:18;i:62588;i:19;i:62343;i:20;i:62589;i:21;i:62343;i:22;i:62590;i:23;i:62343;i:24;i:62343;i:25;i:62343;i:26;i:62592;i:27;i:62343;i:28;i:62593;i:29;i:62343;i:30;i:62594;i:31;i:62343;i:32;i:62343;i:33;i:62595;i:34;i:62343;i:35;i:62343;i:36;i:62597;i:37;i:62343;i:38;i:62343;i:39;i:62343;i:40;i:62343;i:41;i:62343;i:42;i:62343;i:43;i:62343;i:44;i:62343;i:45;i:62600;i:46;i:62343;i:47;i:62343;i:48;i:62601;i:49;i:62343;i:50;i:62602;i:51;i:62602;i:52;i:62603;i:53;i:62343;i:54;i:62604;i:55;i:62343;i:56;i:62605;i:57;i:62343;i:58;i:21700;i:59;i:62602;i:60;i:62602;i:61;i:62687;i:62;i:62343;i:63;i:62602;i:64;i:62602;i:65;i:62689;i:66;i:62343;i:67;i:62602;i:68;i:62602;i:69;i:62602;i:70;i:62602;i:71;i:62602;i:72;i:62602;i:73;i:62602;i:74;i:62690;i:75;i:62343;i:76;i:62602;i:77;i:62602;i:78;i:62602;i:79;i:62602;i:80;i:62602;i:81;i:62602;i:82;i:62602;}

( And thank you for this great plugin and much-needed functionality! )

**Comment by Nikschavan** [comment]
Thank you for reporting the bug @symmetrium 

The post id should not be duplicated on the site, That is a bug. I will probably only save the unique values the the option

**Comment by Nikschavan** [comment]
I have fixed this issue in a branch [issue-17](https://github.com/Nikschavan/unlist-posts/tree/issue-17)

I have tested this already and works as expected.

Will you be also test this @symmetrium ?

**Comment by symmetrium** [comment]
You're welcome - thank you too, for the quick reaction! :))! 

...Just tried it and it worked like a charm :)

**Comment by Nikschavan** [comment]
Thank you for testing this @symmetrium.

I will ship the fix in the next update
