### ISSUE TITLE
Unlist from RSS option?

### ISSUE THREAD

**Issue by smpetrey** [Nikschavan/unlist-posts#20]
Hello! First, this is a fantastic plugin. Very useful for private URLs. 

I have a bit of some plugin feedback I'd like to share. I'd love to see an additional tickbox that controls publish visibility in RSS. Something like this:

![example-unlist-options](https://user-images.githubusercontent.com/6411509/38201574-cae219bc-3666-11e8-89bc-6109bbff1599.jpg)

In the above example, users can publish unlisted posts but RSS subscribers can still see it as fresh content in their feeds. Ticking both boxes however, would leave the URL hidden to public visitors _and_ RSS subscribers. Id' love to hear your thoughts!

Note: this plugin works great with Gutenbergby the way, no compatibility problems in my testing so far.

**Comment by Nikschavan** [comment]
In your use case, do you wish to exclude post unlisting from RSS feed for all posts or this is a post-by-post basis option?

I want to keep the plugin as simple as possible, hence I am thinking of providing a filter that will disable hiding posts from RSS feed.

**Comment by smpetrey** [comment]
Hello! 

I was thinking on a post by post basis, but a filter that would disable hiding posts from RSS would work too! Keeping it simple makes sense to me.

**Comment by Nikschavan** [comment]
@smpetrey The new PR #23 introduces a filter that will allow disabling posts unlist on any query condition. There is also an example filter usage on how you can use this to disable on RSS feed.

**Comment by smpetrey** [comment]
Awesome man!
