### ISSUE TITLE
Tested on Wordpress 5.4.2? 

### ISSUE THREAD

**Issue by Ochaun** [Nikschavan/unlist-posts#36]
Does this plugin have any compatibility issues? I'm getting this banner from the plugin page. 
![image](https://user-images.githubusercontent.com/11700790/88552996-c4dbdd00-cff2-11ea-9596-ad5c2a61f88f.png)

**Comment by Nikschavan** [comment]
This was because the `teste up to` tag in readme.txt was not updated, This has already been updated since https://github.com/Nikschavan/unlist-posts/pull/38 so this warning should not be present anymore.
